#!/bin/bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"
VERSION="$(python3 -c 'import re,pathlib; print(re.search(r"^version\s*=\s*\"([^\"]+)\"", pathlib.Path("pyproject.toml").read_text(), re.M).group(1))')"
STAGE="$(mktemp -d)"
trap 'rm -rf "$STAGE"' EXIT
cp -a docker/debian/. "$STAGE/"
install -d "$STAGE/usr/lib/science-assistant" "$STAGE/usr/share/science-assistant/client" "$STAGE/usr/share/science-assistant/agent" "$STAGE/usr/bin" "$STAGE/lib/systemd/system" "$STAGE/etc/default"
install -m 0755 docker/docker-run.sh "$STAGE/usr/lib/science-assistant/docker-run.sh"
install -m 0755 docker/ensure-mtls-certificates.sh "$STAGE/usr/lib/science-assistant/ensure-mtls-certificates.sh"
install -m 0755 docker/science-assistant-info "$STAGE/usr/bin/science-assistant-info"
install -m 0644 docker/science-assistant-docker.service "$STAGE/lib/systemd/system/science-assistant-docker.service"
install -m 0644 "dist/client-release/wheels/science_assistant_client-${VERSION}-py3-none-any.whl" "$STAGE/usr/share/science-assistant/client/"
install -m 0644 "dist/client-release/wheels/mcp_proxy_adapter-8.10.20-py3-none-any.whl" "$STAGE/usr/share/science-assistant/client/"
install -m 0644 "dist/science-assistant-client-offline-${VERSION}.zip" "$STAGE/usr/share/science-assistant/client/"
install -m 0644 "dist/science-assistant-client-portable-${VERSION}.zip" "$STAGE/usr/share/science-assistant/client/"
install -m 0644 "dist/science-assistant-client-py313-linux-x86_64-${VERSION}.zip" "$STAGE/usr/share/science-assistant/client/"
install -m 0755 "dist/agent-release/mcp_file_parts.py" "$STAGE/usr/share/science-assistant/agent/"
install -m 0755 "dist/agent-release/mcp_file_sender.py" "$STAGE/usr/share/science-assistant/agent/"
install -m 0644 "dist/agent-release/README.md" "$STAGE/usr/share/science-assistant/agent/"
install -m 0644 "dist/agent-release/manifest.json" "$STAGE/usr/share/science-assistant/agent/"
install -m 0644 "dist/science-assistant-agent-${VERSION}.zip" "$STAGE/usr/share/science-assistant/agent/"
sed "s/@VERSION@/$VERSION/g" docker/science-assistant.json.template > "$STAGE/usr/share/science-assistant/science-assistant.json.template"
sed "s/@VERSION@/$VERSION/g" docker/etc-default-science-assistant > "$STAGE/etc/default/science-assistant"
sed -i "s/@VERSION@/$VERSION/g" "$STAGE/DEBIAN/control"
chmod 0755 "$STAGE/DEBIAN/postinst" "$STAGE/DEBIAN/prerm" "$STAGE/DEBIAN/postrm"
mkdir -p dist
dpkg-deb --build --root-owner-group "$STAGE" "dist/science-assistant-docker_${VERSION}_amd64.deb"
echo "dist/science-assistant-docker_${VERSION}_amd64.deb"
